name: flutter_chan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.0

environment:
  sdk: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_html: ^3.0.0-alpha.6
  path_provider: ^2.1.4
  dio: ^5.7.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.2.3
  visibility_detector: ^0.4.0+2
  share_plus: ^7.2.2
  url_launcher: ^6.3.0
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  lint: ^2.3.0
  scrollable_positioned_list: ^0.3.8
  ffmpeg_kit_flutter_full: ^6.0.3
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^8.0.2
  app_settings: ^5.1.1
  modal_bottom_sheet: ^3.0.0
  media_kit: ^1.1.3
  media_kit_video: ^1.1.3
  media_kit_libs_ios_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/ios/media_kit_libs_ios_video_encoders_gpl
  media_kit_libs_macos_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/macos/media_kit_libs_macos_video_encoders_gpl
  media_kit_libs_android_video_encoders_gpl:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: libs/android/media_kit_libs_android_video_encoders_gpl
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/moffatman/media-kit.git
      ref: main
      path: media_kit_video

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon_ios.jpg"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
